// Top-level build file for BlueNote Android (F-Droid & Google Play Store)
buildscript {
    ext {
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 35
        androidxActivityVersion = '1.9.3'
        androidxAppCompatVersion = '1.7.0'
        androidxCoreVersion = '1.15.0'
        androidxWebkitVersion = '1.12.1'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
